PMM-1531 Fixed tablespaces collector for MySQL 8+
percona/mysqld_exporter pull request #74
Opened 2021-02-16 16:27 UTC by percona-csalguero

2021-02-18 10:53 UTC, askomorokhov approved these changes

2021-02-18 10:53 UTC, askomorokhov commented on collector/info_schema_innodb_sys_tablespaces.go
> +	if err != nil {
Just wondering, why you do not check it with `SELECT VERSION();`?

2021-02-18 10:53 UTC, askomorokhov commented on collector/info_schema_innodb_sys_tablespaces.go
> +			innodbTablespacesQuery = innodbTablespacesQueryv80
Should we return innodbTablespacesQuery?

2021-02-18 17:48 UTC, JiriCtvrtka approved these changes

2021-02-19 19:54 UTC, percona-csalguero commented on collector/info_schema_innodb_sys_tablespaces.go
> +			innodbTablespacesQuery = innodbTablespacesQueryv80
No. It is global to fullfil the interface.

2021-02-21 14:12 UTC, BupycHuk requested changes

2021-02-21 14:12 UTC, BupycHuk commented on collector/info_schema_innodb_sys_tablespaces_test.go
> +	innodbTablespacesQuery = innodbTablespacesQueryv57
Why do you set it here? looks like https://github.com/percona/mysqld_exporter/pull/74/files#diff-2350188e094bf6cd7238c12109c42e4e3ac067cda8add719a626fe2dcde325e6R29 should set it by itself and that's what we should test, right?

2021-02-21 14:12 UTC, BupycHuk commented on collector/info_schema_innodb_sys_tablespaces.go
> +	return 8.0
if this scraper is available only for 8.0, I don't understand why do we set innodb tablespaces query?

2021-02-22 15:44 UTC, percona-csalguero commented on collector/info_schema_innodb_sys_tablespaces.go
> +	return 8.0
Not only. It works with 8.0.
There is no min-max versions.

2021-02-22 16:07 UTC, percona-csalguero commented on collector/info_schema_innodb_sys_tablespaces_test.go
> +	innodbTablespacesQuery = innodbTablespacesQueryv57
I've improved the tests.

2021-03-09 14:43 UTC, merged