PMM-7572 Added TLS support for the MySQL connection
percona/mysqld_exporter pull request #75
Opened 2021-03-27 20:40 UTC by percona-csalguero

- Added SSL support for the MySQL connection. 
- Code formatted with gofumports

2021-03-28 14:37 UTC, BupycHuk requested changes

2021-03-28 14:37 UTC, BupycHuk commented on .golangci.yml
> +  disable-all: true
isn't it easier to just disable some linter? It will be consistent with our other golangci configs

2021-03-28 14:37 UTC, BupycHuk commented on collector/custom_query.go
> +	metricMap := make(map[string]MetricMapNamespace)
all these changes may make more conflicts with upstream.

2021-03-28 14:37 UTC, BupycHuk commented on mysqld_exporter.go
> +	mysqlSSLSkipVerify = kingpin.Flag(
as far as I remember we pass this parameter in DSN, don't we?

2021-03-28 14:37 UTC, BupycHuk commented on mysqld_exporter.go
> +		if !strings.Contains(dsn, "?tls=custom") { // maybe it was already added by the config file parser
`tls=custom` can be not the first param in the DSN. I would suggest to parse DSN and then rebuild it. It also will help with overriding `tls` query param

2021-03-28 14:37 UTC, BupycHuk commented on mysqld_exporter.go
> +		if !strings.Contains(dsn, "?tls=custom") { // maybe it was already added by the config file parser
or use `dsnParams` for it.

2021-03-28 14:37 UTC, BupycHuk commented on mysqld_exporter.go
> +	// The parseMycnf function will set the TLS config in case certificates are being defined in
I would include this to else part of the `if` above. Because if users configure via `my.cnf` we should ignore flags.

2021-03-28 14:37 UTC, BupycHuk commented on mysqld_exporter.go
> +	if sslCA != "" {
in case of `my.cnf` we customize TLS only if SSL CA is custom, but in case of flags we customize even if only one of the flags are passed.

2021-03-30 16:10 UTC, percona-csalguero commented on mysqld_exporter.go
> +	mysqlSSLSkipVerify = kingpin.Flag(
we might, but to be consistent, if you specify SSL certs I added this config here too. Otherwise, you have to specify certs here but skip verify in th DSN

2021-03-30 16:12 UTC, percona-csalguero commented on mysqld_exporter.go
> +	// The parseMycnf function will set the TLS config in case certificates are being defined in
No, flags take precedence to cnf. That's how MySQL itself behaves.

2021-03-31 08:54 UTC, askomorokhov approved these changes
Looks good to me. 👍 
Please resolve/respond to comments.

2021-03-31 08:54 UTC, askomorokhov commented on mysqld_exporter.go
> +		dsn = fmt.Sprintf("%s%stls=custom", dsn, sep)
Maybe better to use here "net/url"?

2021-04-06 09:43 UTC, BupycHuk requested changes

2021-04-06 09:43 UTC, BupycHuk commented on collector/custom_query.go
> +	metricMap := make(map[string]MetricMapNamespace)
maybe it's better to revert it?

2021-04-06 09:43 UTC, BupycHuk commented on mysqld_exporter.go
> +	if sslCA != "" {
The question is: why it's inconsistent?

2021-04-06 09:43 UTC, BupycHuk commented on mysqld_exporter.go
> +		if !strings.Contains(dsn, "tls=custom") { // maybe it was already added by the config file parser
What if `DATA_SOURCE_NAME` contains `tls=verify-data` or any other value?

2021-04-06 09:43 UTC, BupycHuk commented on mysqld_exporter_test.go
> +func TestSSL(t *testing.T) {
Can we add more tests with different DSNs and `my.cnf` files to check logic?

2021-04-06 09:43 UTC, BupycHuk commented on mysqld_exporter.go
> +		dsn = fmt.Sprintf("%s%stls=custom", dsn, sep)
+1

2021-04-06 11:47 UTC, percona-csalguero commented on mysqld_exporter.go
> +	if sslCA != "" {
You are right. Thanks .

2021-04-06 12:36 UTC, percona-csalguero commented on mysqld_exporter.go
> +		dsn = fmt.Sprintf("%s%stls=custom", dsn, sep)
I used the driver's own parser func.

2021-04-06 12:39 UTC, percona-csalguero commented on mysqld_exporter_test.go
> +func TestSSL(t *testing.T) {
Added.

2021-04-08 08:52 UTC, JiriCtvrtka approved these changes

2021-04-29 12:53 UTC, merged