Fix: CS0017871 - Multi-request protection breaks metrics gathering
percona/mysqld_exporter pull request #78
Opened 2021-05-13 06:19 UTC by fmbiete

Prometheus exporter have 3 gathering operations (low, medium, high) that can and will overlap. Protections to avoid multiple simultaneous collection should contemplate those 3 types.

2021-05-13 06:20 UTC, it-percona-cla commented
[![CLA assistant check](https://cla-assistant.percona.com:443/pull/badge/not_signed)](https://cla-assistant.percona.com:443/percona/mysqld_exporter?pullRequest=78) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.percona.com:443/percona/mysqld_exporter?pullRequest=78) before we can accept your contribution.<br/><hr/>**Francisco Miguel Biete Banon** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.percona.com:443/check/percona/mysqld_exporter?pullRequest=78) it.</sub>

2021-05-25 16:01 UTC, BupycHuk requested changes
Hi @fmbiete, thank you for your contribution. Could you fix some linter issues, please?

2021-05-25 16:01 UTC, BupycHuk commented on mysqld_exporter.go
> +        log.Infof("REQUEST FAILED: %q %v", r.URL.Path, r.URL.Query())
please change log level to warn.

2021-05-25 16:01 UTC, BupycHuk commented on mysqld_exporter.go
> +        log.Infof("REQUEST FAILED: %q %v", r.URL.Path, r.URL.Query())
please change log level to warn.

2021-05-25 16:01 UTC, BupycHuk commented on mysqld_exporter.go
> +        log.Infof("REQUEST FAILED: %q %v", r.URL.Path, r.URL.Query())
please change log level to warn.

2021-05-25 16:01 UTC, BupycHuk commented on mysqld_exporter.go
> +    defer func() { log.Infof("REQUEST ELAPSED TIME: %v %s", time.Since(start), query_collect) }()
please change log level to debug.

2021-05-27 22:32 UTC, percona-csalguero requested changes
Please address the requested changes. 
Thanks !

2021-05-28 08:06 UTC, fmbiete commented on mysqld_exporter.go
> +  processing_mr := false
Please review the rest, when I format the file all the lines get changed

2021-05-28 08:18 UTC, fmbiete commented
This should address what you requested.
Formatting the file changes all the lines in it, if you want I can do that after you complete the review

2021-05-28 16:54 UTC, percona-csalguero commented
Hi @fmbiete .
These changes look good. I ran the tests and they are passing.
Just in case, I am leaving the output here as an example.
One more thing. Could you please run `make format` and commit the changes?

Thanks 
```
make env-up
Creating network "mysqld_exporter_default" with the default driver
Creating mysqld_exporter_db ... done
 karl  karl-OMEN  ~/…/mysqld_exporter   fmbiete-fix_multi_request_protection  ✎  $  make test
>> running tests
ok      github.com/percona/mysqld_exporter      8.343s
ok      github.com/percona/mysqld_exporter/collector    1.620s
```

2021-05-28 18:47 UTC, fmbiete commented
There you go

2021-05-31 11:37 UTC, BupycHuk approved these changes

2021-05-31 18:27 UTC, percona-csalguero approved these changes

2021-06-01 12:23 UTC, askomorokhov approved these changes

2021-06-01 12:24 UTC, merged

2021-12-03 15:09 UTC, Aleksa-del commented
@fmbiete Hello! We would love to send you a gift from Percona for your contribution. Please, contact us at community-team@percona.com