PMM-9337 Update Go 1.17
percona/mysqld_exporter pull request #89
Opened 2021-12-23 23:51 UTC by BupycHuk

2021-12-29 10:53 UTC, JiriCtvrtka approved these changes

2021-12-30 10:28 UTC, percona-csalguero approved these changes

2021-12-30 10:43 UTC, ShashankSinha252 approved these changes
LGTM

2021-12-30 11:06 UTC, ShashankSinha252 requested changes
Needs update to **go.mod** in **tools** package

2022-01-02 19:06 UTC, ShashankSinha252 approved these changes

2022-01-03 12:06 UTC, merged